### ISSUE TITLE
mBox.Core close() does not destroy mBox elements

### ISSUE THREAD

**Issue by philipp-winterle** [stephanwagner/mBox#1]
If the close() function is called the mBox\* elements remain in the DOM. 

I would suggest either using the complete function in the close function or dealing the the systemCloseComplete event in the modal class, because this is the one which doesnt remove the elements. Maybe its wantet but I prefer removing unused elements.

**Comment by stephanwagner** [comment]
It is intended that the mBox is not removed from the DOM. If you remove it
from the DOM the mBox will always be created again when you open it with the
open() function.

Line 321:

open: function(options) {
if(!this.wrapper) {
// construct the mBox
this.construct();
}

Only the mBox.Notice will destroy the mBox because a notice should only
show once.

But if you do want to remove it from the DOM when it is closed, I recommend
to write this in the closeComplete event:

new mBox({

```
// options
```

   onCloseComplete: function() {
        this.destroy();
    }

});

On Fri, May 25, 2012 at 12:50 PM, hummal <
reply@reply.github.com

**Comment by philipp-winterle** [comment]
That onCloseComplete function in the options is the right way. I need this behaviour because I want to create a new mBox every time i receive a message and the content is different every time.

But you gave me a hint.
