### ISSUE TITLE
Tooltip seems to fail at deactivating the browser native title tooltip

### ISSUE THREAD

**Issue by twincascos** [stephanwagner/mBox#4]
Using: mootools 1.4.5
mBox 0.2.5
mBox.Tooltip

firefox 16,
Safari 5.0.6
Crome 20.0.1132.47

The browser native tooltip continues to appear along with the mBox Tooltip when pulling the tooltip from the link's title attribute.
I don't think that this is an intended function.
I'm looking at adding a bit of code to the launcher to store then remove then return the title attribute from each link, But it seams like something the mBox tooltip class should be doing automatically.

Maybe it's just my set up...
I'm using this in the options:
attach:  $$('*[title]'), // anything with a title
setContent: 'title', // use the title as tip

perhaps there's a better way to tell mBox.tooltip to get the title attribute of the link?

**Comment by stephanwagner** [comment]
Hi, sorry for the late reply, but im incredibly busy at work at the moment.
You are right, when using the title as attribute you will have both tooltips, the mBox and your Browsers default. I never actually thought about using the title attribute.

I will leave this issue open for now and will add the feature that the title attribute will be removed when the mBox uses it. Thanks for mentioning.

**Comment by stephanwagner** [comment]
Well, I was going to implement this in Version 0.2.6.
The issue I came across is, that when I remove the title attribute when the mBox is being attached, it wont get loaded as content. There are several workarounds I could do, but I decided to leave it out for now, i've put it on my maybe list.

The easiest thing how you could solve this on your side is to just instead of title="My Text", use data-title="My text". This is html5 conform and the browsers native title wont be shown.
